version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "AutoFixture"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
